language: elixir

services:
  - postgresql

addons:
  postgresql: "9.4"

elixir:
  - 1.5
  - 1.4

otp_release:
  - 20.1
  - 19.3

env:
  global:
    - DB=pgsql
    - MIX_ENV=test

notifications:
  email: false

sudo: false

before_script:
  - psql -c 'create database ecto_role_test;' -U postgres

script:
  - mix test


after_script:
   - MIX_ENV=docs mix deps.get
   - MIX_ENV=docs mix inch.report